/**
 * Job types for Ordaro background job processing
 */
export enum ORDARO_JOB_TYPES {
  // Order Processing
  PROCESS_WHATSAPP_ORDER = 'PROCESS_WHATSAPP_ORDER',
  SEND_ORDER_NOTIFICATION = 'SEND_ORDER_NOTIFICATION',
  PROCESS_ORDER_PAYMENT = 'PROCESS_ORDER_PAYMENT',

  // Notifications
  SEND_EMAIL = 'SEND_EMAIL',
  SEND_AUTH0_EMAIL = 'SEND_AUTH0_EMAIL',
  SEND_SMS = 'SEND_SMS',
  SEND_PUSH_NOTIFICATION = 'SEND_PUSH_NOTIFICATION',

  // Inventory & Sync
  SYNC_INVENTORY = 'SYNC_INVENTORY',
  SYNC_BRANCH_DATA = 'SYNC_BRANCH_DATA',

  // Analytics
  AGGREGATE_ANALYTICS = 'AGGREGATE_ANALYTICS',
  GENERATE_REPORT = 'GENERATE_REPORT',

  // User Management
  SEND_INVITATION_EMAIL = 'SEND_INVITATION_EMAIL',
  SEND_WELCOME_EMAIL = 'SEND_WELCOME_EMAIL',
}
